#deploysAzureVM.yaml
---
- hosts: localhost
  connection: local

  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: AnsibleDevops-rg
        location: westus
      register: AnsibleDevopsrg
    - debug: 
        var: AnsibleDevopsrg

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: AnsibleDevops-rg
        name: AnsibleDevops-rg-vNet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: AnsibleDevops-rg
        name: AnsibleDevops-rg-webSubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: AnsibleDevops-rg-vNet
      - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: AnsibleDevops-rg
        allocation_method: Static
        name: DeploymentServer-Jenkins-Docker-Sonar-webPublicIP
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: AnsibleDevops-rg
        name: DeploymentServer-Jenkins-Docker-Sonar-NSG
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_vm'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Inbound
          - name: 'allow_vm-egress'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Outbound                     

    - name: Create a network interface
      azure_rm_networkinterface:
        name: DeploymentServer-Jenkins-Docker-Sonar-webNic
        resource_group: AnsibleDevops-rg
        virtual_network: AnsibleDevops-rg-vNet
        subnet_name: AnsibleDevops-rg-webSubnet
        security_group: DeploymentServer-Jenkins-Docker-Sonar-NSG
        ip_configurations:
          - name: default
            public_ip_address_name: DeploymentServer-Jenkins-Docker-Sonar-webPublicIP
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: AnsibleDevops-rg
        name: DeployServer-Jenkins-Docker-Sonarqube
        vm_size: Standard_D2s_v3
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: < insert yor ssh public key here... using "ssh-keygen" get the ssh-rsa and give here>
        network_interfaces: DeploymentServer-Jenkins-Docker-Sonar-webNic
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
     - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: AnsibleDevops-rg
        allocation_method: Static
        name: TestServer-webPublicIP
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: AnsibleDevops-rg
        name: TestServer-NSG
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_vm'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Inbound
          - name: 'allow_vm-egress'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Outbound                     

    - name: Create a network interface
      azure_rm_networkinterface:
        name: TestServer-webNic
        resource_group: AnsibleDevops-rg
        virtual_network: AnsibleDevops-rg-vNet
        subnet_name: AnsibleDevops-rg-webSubnet
        security_group: TestServer-NSG
        ip_configurations:
          - name: default
            public_ip_address_name: TestServer-webPublicIP
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: AnsibleDevops-rg
        name: TestServer
        vm_size: Standard_D2s_v3
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: < insert yor ssh public key here... using "ssh-keygen" get the ssh-rsa and give here>
        network_interfaces: TestServer-webNic
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: AnsibleDevops-rg
        name: AnsibleDevops-rg2-vNet
        location: westus2
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: AnsibleDevops-rg
        name: AnsibleDevops-rg2-webSubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: AnsibleDevops-rg2-vNet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: AnsibleDevops-rg
        location: westus2
        allocation_method: Static
        name: ProdServer-webPublicIP
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: AnsibleDevops-rg
        location: westus2
        name: ProdServer-NSG
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_vm'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Inbound
          - name: 'allow_vm-egress'
            protocol: "*"
            destination_port_range: 
              - 8080
              - 9000
            access: Allow
            priority: 350
            direction: Outbound                     

    - name: Create a network interface
      azure_rm_networkinterface:
        name: ProdServer-webNic
        location: westus2
        resource_group: AnsibleDevops-rg
        virtual_network: AnsibleDevops-rg2-vNet
        subnet_name: AnsibleDevops-rg2-webSubnet
        security_group: ProdServer-NSG
        ip_configurations:
          - name: default
            public_ip_address_name: ProdServer-webPublicIP
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: AnsibleDevops-rg
        name: ProdServer
        location: westus2
        vm_size: Standard_D2s_v3
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: < insert yor ssh public key here... using "ssh-keygen" get the ssh-rsa and give here>
        network_interfaces: ProdServer-webNic
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
